-- Select the Schema
use inspection;

-- Checking the dataset again 
SELECT * FROM inspection;

-- CTE1 for analysis
SELECT PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE, COST_OF_INSPECTION_IN_DOLLARS
FROM inspection;

-- CTE2 STR_TO_DATE
SELECT 
	PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME, 
    STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS "DATE", 
    COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST
FROM inspection;

-- FINAL query to analyze
WITH CTE AS
(
SELECT 
	PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
    STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST, 
    LAG(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y'),1) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_DATE,
    LAG(COST_OF_INSPECTION_IN_DOLLARS,1) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_COST,
    COST_OF_INSPECTION_IN_DOLLARS - LAG(COST_OF_INSPECTION_IN_DOLLARS,1) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS CHANGE_IN_COST,
	ROUND((COST_OF_INSPECTION_IN_DOLLARS - LAG(COST_OF_INSPECTION_IN_DOLLARS,1) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y'))) 
    / LAG(COST_OF_INSPECTION_IN_DOLLARS,1) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) * 100, 2) AS PERCENT_CHANGE
FROM inspection
)

SELECT *
FROM CTE
WHERE 1=1
    AND CHANGE_IN_COST > 0 
    AND SECOND_MR_INSPECTION_COST IN (SELECT MAX(SECOND_MR_INSPECTION_COST) FROM CTE GROUP BY PHA_NAME);